version: "3"
services:

  api:
    build: api
    container_name: "api"
    volumes:
      - .:/app
    links:
      - mongo
    ports:
      - "8008:8008"

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongo
    ports:
      - 3300:3000